language: ruby

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1

dist: xenial
osx_image: xcode11

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libfoma-dev
  homebrew:
    packages:
      - foma

before_install:
  - gem install bundler -v 2.1.4

script:
  - rake
  - bundle exec rubocop --version
  - bundle exec rubocop -S -E
