language: ruby
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
dist: xenial
os: linux
before_install:
  - sudo apt-get install -y libfoma-dev
script:
  - echo "Rubocop $(bundle exec rubocop --version)"
  - bundle exec rubocop -S -E
