# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "foma"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marius L. J\u{f8}hndal"]
  s.date = "2012-08-16"
  s.description = "A wrapper for the FOMA finite state library"
  s.email = "mariuslj (at) ifi [dot] uio (dot) no"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/extconf.rb",
    "ext/foma.c",
    "foma.gemspec",
    "test/.gitignore",
    "test/test_foma.bin",
    "test/test_foma.rb"
  ]
  s.homepage = "http://github.com/mlj/ruby-foma"
  s.require_paths = ["lib"]
  s.rubyforge_project = "foma"
  s.rubygems_version = "1.8.11"
  s.summary = "FOMA finite state library interface"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

